version: "3"
services:
  # backend:
  #   build: .
  #   ports:
  #     - "${PORT:-8000}:${PORT:-8000}"
  #   env_file:
  #     - .env

  database:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./full_create.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "80:80"

volumes:
  pgdata:
